version: '1.0'

services:
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  book_store_app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb-data: